[build]
  command = "npm install"
  functions = "netlify/functions" # <-- Yeni fonksiyonlar klasörü

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat" # Bu kural hala geçerli, products.js'i bulacak
  status = 200
  force = true